name: Supabase Keep-Alive

on:
    schedule:
        # Se ejecuta automáticamente cada 3 días a las 08:00 AM UTC
        - cron: "0 8 */3 * *"
    # Te permite probarlo manualmente desde el panel de GitHub cuando quieras
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping a la web
              run: curl -s https://stack-one-tfg.vercel.app/ > /dev/null
